### ISSUE TITLE
🐞WORKMAGER d does not work closing the application

### ISSUE THREAD

**Issue by flutteresbolivia** [fluttercommunity/flutter_workmanager#264]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |       0.4.0        |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
I cannot describe the error, because I close the application and cannot debug

**Output of `flutter doctor -v`**

**Comment by ened** [comment]
Do you have any stack trace, error logs or plug-in behavior which you could share? More details are needed in order to debug this ticket..

**Comment by sumitbhanushali** [comment]
I am facing same problem

**Comment by flutteresbolivia** [comment]
> ¿Tiene algún seguimiento de pila, registros de errores o comportamiento de complemento que pueda compartir? Se necesitan más detalles para depurar este ticket.

I cannot show the errors, because I am in production in the play Store, but I have noticed that it does not work on Xioami phones. and Samsumg phones work normal.

**Comment by ened** [comment]
Some phone makers override behavior for background processes. Please check out https://dontkillmyapp.com  for some recommendations and workarounds.

`workmanager` may not be the best plugin for every use case, too. If you need continuous background operation, it may be best to run a android foreground service. See https://pub.dev/packages/flutter_background for a great implementation. This will start a ongoing notification (due to the foreground service) which keeps your App alive.

You may still face problems with certain phone makers though. 

Please let me know if this helps.

**Comment by flutteresbolivia** [comment]
@ened 
I bought an s10 plus phone.

I just tried flutter_background and when I close the application the notification also closes.

I have seen in some applications that when the app is completely closed, a notification remains on the screen.

**Comment by ened** [comment]
@flutteresbolivia Can you define a bit more what you mean by "Close Application"?
