### ISSUE TITLE
Is there a way to determine whether the app is running or not?

### ISSUE THREAD

**Issue by alexursul** [fluttercommunity/flutter_workmanager#333]
Hi! Is there a way to determine whether the app is running right now in the foreground or not during an execution of the background task?
I need to get some jobs done only when an user is not using the app right now. I tried to use `requiresDeviceIdle: true`, but with this option my background tasks don't fire at all.

**Comment by clragon** [comment]
It seems that the `lifecycleState` does in fact _not_ reflect whether the app is currently running or not.
I assume because we are on different isolates and have different widget bindings.
No matter, it seems that my workmanager callback always get `detached`, regardless of there being an instance of the app running in foreground or not.

**Comment by ened** [comment]
@clragon in that case please try the native app state plug-in above and extend it - prs welcome

**Comment by joharputr** [comment]
any update?
