### ISSUE TITLE
does work manager handles "finish" or closing of task automatically ?

### ISSUE THREAD

**Issue by reachenbee** [fluttercommunity/flutter_workmanager#465]
does work manager handles "finish" or closing of task automatically ?
did not find anything in the docs.

got below error  while using Workmanager().registerOneOffTask(

[BackgroundTask] Background Task 27 ("##"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Comment by reachenbee** [comment]
https://developer.apple.com/forums/thread/695910

**Comment by marcoancona** [comment]
I am not sure why this issue was first closed, then marked as "not planned". I see the same warning in the console, for tasks that _complete way before 30 seconds_. I believe the original issue is not about how to make background tasks run longer than 30 seconds (which is not possible), but rather whether the library correctly calls UIApplication.endBackgroundTask upon completion of the task and, if not, if this could cause the system to grant less background space to the app. @ened do you have any idea about this?
